"""drop cleared column

Revision ID: 1aa83cc20783
Revises: 
Create Date: 2025-08-16 12:20:32.971336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa83cc20783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_settled'), table_name='ledger_entries')
    op.drop_column('ledger_entries', 'settled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('settled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_ledger_entries_settled'), 'ledger_entries', ['settled'], unique=False)
    # ### end Alembic commands ###
