"""initial schema

Revision ID: 9301254028ea
Revises: 
Create Date: 2025-09-14 13:05:46.973227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9301254028ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_creditor_id'), 'ledger_entries', ['creditor_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_debtor_id'), 'ledger_entries', ['debtor_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_guild_id'), 'ledger_entries', ['guild_id'], unique=False)
    op.create_table('reminder_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_entries_creator_id'), 'reminder_entries', ['creator_id'], unique=False)
    op.create_index(op.f('ix_reminder_entries_guild_id'), 'reminder_entries', ['guild_id'], unique=False)
    op.create_index(op.f('ix_reminder_entries_partner_id'), 'reminder_entries', ['partner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_entries_partner_id'), table_name='reminder_entries')
    op.drop_index(op.f('ix_reminder_entries_guild_id'), table_name='reminder_entries')
    op.drop_index(op.f('ix_reminder_entries_creator_id'), table_name='reminder_entries')
    op.drop_table('reminder_entries')
    op.drop_index(op.f('ix_ledger_entries_guild_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_debtor_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_creditor_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
